"""empty message

Revision ID: 127fc16e3f87
Revises: 257553665ff5
Create Date: 2024-05-17 18:07:52.986466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127fc16e3f87'
down_revision = '257553665ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
